### ISSUE TITLE
Add your favorite links to "links" 

### ISSUE THREAD

**Issue by UnicornRiley** [UnicornRiley/MFWSOGH#1]
Add your favorite links to the file "links"

**Comment by siddas27** [comment]
what kind of links?

**Comment by UnicornRiley** [comment]
Any types you think are interesting or enjoy. I plan on having multiple
categories I want a variety of topics on the site and am open to pretty
much anything

**Comment by deveshd2k** [comment]
I can also add some links. Can I work on this?

**Comment by deveshd2k** [comment]
Please review #23

**Comment by rannieo** [comment]
Hey, i added some links in your project. please check my page. Thanks

**Comment by Naman9639** [comment]
Please review my PR https://github.com/UnicornRiley/MFWSOGH/pull/26

**Comment by UnicornRiley** [comment]
Thank you all for the links, I'll take the rest of the pull requests for "links" and add them (as they piled up and cause conflicts so I'll edit the files and merge)
